### ISSUE TITLE
Refactor components into common directory

### ISSUE THREAD

**Issue by awaseem** [awaseem/cursor#3]
There are quite a few components that are used in a lot places that don't exist in the `common` directory. I structured the `components` directory to be per screen based, but with some overlapping I decided to put them in a common directory. 

The problem is that, after some time I started using components all over the place. Would love to refactor them back into the common directory

**Comment by awave1** [comment]
I'd like to help with that. The project looks pretty interesting and I wanna help as much as I can

**Comment by awaseem** [comment]
👋 @awave1 Thanks for helping, let me know if you have any questions! This shouldn't be too hard, but you never know 🤷. Basically I just want to move some of the components within the `course` folder to `common`. Best to look at all the screens and see if a component is used more than twice, and move it to the common folder, rename it and change the path.

**Comment by awave1** [comment]
got it @awaseem, will let you know if anything comes up
